- include_tasks: mirror-user.yml

- import_role:
    name: httpd

- name: Adding vhost file
  template:
    src: 10_mirror_msync.conf.j2
    dest: /etc/httpd/conf.d/10_mirror_msync.conf
  notify:
    - restart_httpd

- name: Adding specific vhost (only for also public external mirror role)
  template:
    src: 11_mirror_public.conf.j2
    dest: /etc/httpd/conf.d/11_mirror_public.conf
  when: mirror_external_vhost  
  notify:
    - restart_httpd
 
- name: Ensuring some selinux booleans are enabled
  seboolean:
    name: "{{ item }}"
    persistent: yes
    state: yes
  with_items:
    - httpd_enable_homedirs
    - httpd_read_user_content

- name: Script to gather mirror content
  template:
    src: rsync-master-full.j2
    dest: "/home/{{ mirror_local_user }}-scripts/rsync-master-full"
    mode: 0755

- name: Cron job to rsync content from upstream node
  cron:
    name: "CentOS mirror rsync job"
    job: "/home/{{ mirror_local_user }}-scripts/rsync-master-full {{ mirror_rsync_from }} > /dev/null 2>&1"
    minute: "*/12"
    user: "{{ mirror_local_user }}"
  tags:
    - cron

- include_tasks: rsyncd.yml
  when: mirror_rsyncd
  tags:
    - rsyncd

- include_tasks: monitoring.yml  
