- block:
  - name: Configuring agent in Zabbix server
    include_role:
      name: zabbix-server
      tasks_from: agent_config
    vars:
      zabbix_templates: "{{ mirror_zabbix_templates }}"
      zabbix_groups: "{{ mirror_zabbix_groups }}"
    tags:
      - monitoring
  delegate_to: "{{ zabbix_api_srv }}"  
  when: zabbix_api_srv is defined

- name: Zabbix check for mirror age
  template:
    src: zabbix-check-msync-status.sh.j2
    dest: /usr/lib/zabbix/zabbix-check-msync-status.sh
    mode: 0750

- name: Zabbix cron jobs
  cron:
    name: Mirror content status
    job: /usr/lib/zabbix/zabbix-check-msync-status.sh
    minute: "*/5"
